### ISSUE TITLE
 O/X 퀴즈

### ISSUE THREAD

**Issue by mozodev** [creativecommonskorea/cclguide#9]
- O, X 퀴즈 노출 순서 O->X, X->O
- O/X 퀴즈 구성을 O 퀴즈로만 혹은 X 퀴즈로만 노출  
  예를 들어 어떤 페이지의 O/X 퀴즈는 답이 O 인 퀴즈로만 노출

> O, X를 지정할 수 있게 메타데이터 필드 지정. 
>   퀴즈 o / 퀴즈 x 가 아니라 퀴즈 1 (o/x 지정) 퀴즈 2 (o/x 지정)
- O/X  퀴즈를 1개 혹은 3개

결정 필요
- 3개가 최대인지 그 이상이 될 수 있는지?
- 홀수인 경우 디자인? 3단 아니면 2단인 상태에서 밑으로 흐를지?

이 이슈는 요걸 결정한 후에 해결하겠습니다.
@jyoh0131 @nanshil

**Comment by mozodev** [comment]
10개 /  2단 흐르기

**Comment by mozodev** [comment]
@jyoh0131 
퀴즈 입력하는 방식을 수정했습니다. 기존 퀴즈 o, 퀴즈 x 이런 필드는 모두 없애고 맨 아래 원시 데이터 필드를 사용합니다.

prose.io 메타데이터에서 입력 필드에서 아래와 같이
원시 메타데이터 (raw metadata) 입력 필드에 아래 코드와 같이 입력하시면 됩니다.
순서는 잘라내서 앞뒤로 이동하면 그대로 출력합니다.
o/x는 o/x가 이미지인데 이미지 명이 right/wrong으로 되어 있어서 answer 란에 right / wrong으로 입력해야 합니다. 

![2016-01-22 10 49 24](https://cloud.githubusercontent.com/assets/1661950/12512234/6bfdb8da-c15a-11e5-9e6b-35d5bc3b87a6.png)

```
quiz:
  - title: "CC-BY-SA 이미지를 CC-BY 블로그에 가져다 쓸 수 있다."
    answer: right
    description: |
      "예, 쓸 수 있습니다. SA는 동일조건변경허락으로 이미지를 크롭하거나 다른 것과 합성하는 등 변경하지 않는다면 반드시 BY-SA의 조건을 그대로 가져올 필요는 없습니다. 단, 변경을 할 시에는 BY-SA를 블로그와 별개로 이미지에 표기해주셔야 합니다."
  - title: CC 라이선스는 저작권에 반대하는 라이선스이다.
    answer: wrong
    description: |
      CC는 저작권에 반대하는 것이 아닙니다. CCL은 저작권자로 하여금 좀 더 유연하고 열린 방법으로 저작권을 보유하고 관리할 수 있도록 도와줍니다. 사실 CCL은 그 실효성을 저작권법에 의존하고 있습니다.
  - title: "CC-BY-SA 이미지를 CC-BY 블로그에 가져다 쓸 수 있다."
    answer: right
    description: |
      "예, 쓸 수 있습니다. SA는 동일조건변경허락으로 이미지를 크롭하거나 다른 것과 합성하는 등 변경하지 않는다면 반드시 BY-SA의 조건을 그대로 가져올 필요는 없습니다. 단, 변경을 할 시에는 BY-SA를 블로그와 별개로 이미지에 표기해주셔야 합니다."
  - title: CC 라이선스는 저작권에 반대하는 라이선스이다.
    answer: wrong
    description: |
      CC는 저작권에 반대하는 것이 아닙니다. CCL은 저작권자로 하여금 좀 더 유연하고 열린 방법으로 저작권을 보유하고 관리할 수 있도록 도와줍니다. 사실 CCL은 그 실효성을 저작권법에 의존하고 있습니다.
```

코드 편집기에서 수정해서 푸시하는 경우는 front matter 부분에 위의 형식으로 추가하면 됩니다.

**Comment by mozodev** [comment]
```
quiz:
  - title: 
    answer: 
    description: |
  - title: 
    answer: 
    description: |
```

원고 입력 구조입니다. 
주의할 점은 줄바꿀 때 마다 위의 뎁스 기준으로 스페이스 2개 추가로 들여써야 한다는 점입니다.
| 요 막대기의 의미는 행바꿈을 인식하는 겁니다. 

예를 들어

```
  description: | (스페이스 2개)
    CC는 저작권에 반대하는 것이 아닙니다. (스페이스 4개)
    CCL은 저작권자로 하여금 좀 더 유연하고 열린 방법으로 저작권을 보유하고  (스페이스 4개)
    관리할 수 있도록 도와줍니다. 사실 CCL은 그 실효성을 저작권법에 의존하고 있습니다. (스페이스 4개)
```

요렇게 입력하면 줄바꿈을 그대로 출력해줍니다. 줄바꿈 안하시면 막대기 없이 옆으로 죽 늘여서 적으시면 됩니다. 
막대기 없이 줄바꿈하면 에러가 나서 인식하지 못해 출력하지 않습니다.
